import { motion } from "framer-motion";
import { Scale, AlertTriangle } from "lucide-react";

const sections = [
  {
    number: "1",
    title: "Acceptance of Terms",
    body: `These Terms of Use ("Terms") constitute a legally binding agreement between you ("User") and Sonuria, Inc. ("Company," "we," "us"). By accessing the Sonuria platform (the "Service"), you acknowledge that you have read, understood, and agree to be bound by these Terms, our Privacy Policy, and our Acceptable Use Policy.`,
  },
  {
    number: "2",
    title: "Eligibility & Age Representation",
    body: `The Service is strictly restricted to individuals aged eighteen (18) and older. By using the Service, you represent that you meet this age requirement.`,
    items: [
      {
        label: "Verification",
        text: "The Company reserves the right to employ third-party age verification services. You agree to provide valid government-issued identification upon request. If we have reason to believe you are under 18, your account will be terminated immediately without notice or refund.",
      },
      {
        label: "Prohibited Users",
        text: "You may not use this site if you are a convicted sex offender or if your account has been previously disabled for violations of law or our policies.",
      },
    ],
  },
  {
    number: "3",
    title: "Nature of AI Interaction & Disclaimer",
    body: `All interactions on the Service are generated by Artificial Intelligence ("AI"). All personas, characters, and biographies are purely fictional constructs. You agree that:`,
    items: [
      {
        label: "Simulated Interaction",
        text: `No real-world relationship exists between you and any AI persona. Any claims of "real-world" identity, location, or feelings are fictional and part of the roleplay experience.`,
      },
      {
        label: "No Professional Advice",
        text: "AI-generated content is for entertainment only. It does not constitute professional, medical, legal, or financial advice.",
      },
      {
        label: "Emotional Reliance",
        text: "The Company is not liable for any emotional distress or psychological reliance on the AI arising from your use of the Service.",
      },
    ],
  },
  {
    number: "4",
    title: `Embers & Financial Terms`,
    body: `The Service utilizes a credit-based system called "Embers."`,
    items: [
      {
        label: "4.1 — Non-Refundability",
        text: `All purchases of Embers are final. Embers have no cash value, are non-transferable, and are non-refundable regardless of account termination or service interruption.`,
      },
      {
        label: "4.2 — Chargebacks",
        text: "Any unauthorized chargeback is considered a material breach of this Agreement. We reserve the right to permanently ban the User's identity from the Service and report such activity to global fraud prevention databases. A $50.00 administrative fee will be applied to any contested transaction.",
      },
      {
        label: "4.3 — Subscriptions",
        text: "If you opt into a recurring subscription, it will automatically renew until cancelled in your account settings.",
      },
    ],
  },
  {
    number: "5",
    title: "Limitation of Liability",
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SONURIA, INC. SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES (INCLUDING EMOTIONAL DISTRESS) ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THESE TERMS SHALL NOT EXCEED THE GREATER OF $250.00 USD OR THE TOTAL FEES PAID BY THE USER IN THE PRECEDING SIX (6) MONTHS.`,
  },
  {
    number: "6",
    title: "Indemnification",
    body: `User agrees to indemnify and hold harmless Sonuria, Inc. and its affiliates, officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and legal fees (including reasonable attorneys' fees) resulting from User's violation of these Terms or the Acceptable Use Policy.`,
  },
  {
    number: "7",
    title: "Governing Law & Dispute Resolution",
    body: `This Agreement is governed by the laws of the State of Delaware. This Agreement contains a binding arbitration clause and a class action waiver that affects your legal rights. You agree that any dispute must first be submitted to mandatory mediation for at least 60 days before any legal action is filed. You waive any right to participate in a class action lawsuit or class-wide arbitration.`,
  },
];

export function Terms() {
  return (
    <div className="min-h-screen pt-0 pb-24 bg-mesh">
      {/* Ambient glows */}
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="absolute top-0 right-1/4 w-[500px] h-[500px] bg-primary/6 blur-[160px] rounded-full" />
        <div className="absolute bottom-0 left-1/4 w-[400px] h-[400px] bg-accent/5 blur-[140px] rounded-full" />
      </div>

      <div className="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="text-center mb-10"
        >
          <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-primary/30 to-accent/20 border border-primary/20 flex items-center justify-center mx-auto mb-6">
            <Scale className="w-6 h-6 text-primary/70" />
          </div>
          <h1 className="font-display text-4xl font-semibold italic text-white/90 mb-3">
            Terms of Use
          </h1>
          <p className="text-muted-foreground/50 font-light text-sm">
            Sonuria, Inc. · A Delaware Corporation · Last updated April 27, 2026
          </p>
        </motion.div>

        {/* Arbitration warning notice */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15, duration: 0.5, ease: "easeOut" }}
          className="flex items-start gap-4 rounded-2xl border border-primary/25 bg-primary/8 px-6 py-5 mb-10"
        >
          <AlertTriangle className="w-5 h-5 text-primary/70 flex-shrink-0 mt-0.5" />
          <p className="text-sm font-light text-white/70 leading-relaxed">
            <span className="font-semibold text-white/85">Important notice: </span>
            This agreement contains a{" "}
            <span className="text-white/85">binding arbitration clause</span> and a{" "}
            <span className="text-white/85">class action waiver</span>. These provisions affect your legal rights. Please read the full Terms carefully before using the Service.
          </p>
        </motion.div>

        {/* Sections */}
        <div className="space-y-6">
          {sections.map((section, i) => (
            <motion.div
              key={section.number}
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 + i * 0.07, duration: 0.5, ease: "easeOut" }}
              className="glass-panel rounded-2xl p-7"
            >
              <div className="flex items-start gap-4 mb-4">
                <span className="flex-shrink-0 w-7 h-7 rounded-lg bg-primary/15 border border-primary/20 flex items-center justify-center text-xs font-semibold text-primary/80 font-display">
                  {section.number}
                </span>
                <h2 className="font-display text-lg font-semibold italic text-white/85 leading-snug pt-0.5">
                  {section.title}
                </h2>
              </div>

              <div className="pl-11">
                {section.body && (
                  <p className={`text-muted-foreground/70 font-light text-sm leading-relaxed ${section.items ? "mb-4" : ""}`}>
                    {section.body}
                  </p>
                )}

                {section.items && (
                  <ul className="space-y-4">
                    {section.items.map((item) => (
                      <li key={item.label}>
                        <span className="text-white/60 font-medium text-sm">
                          {item.label}:{" "}
                        </span>
                        <span className="text-muted-foreground/65 font-light text-sm leading-relaxed">
                          {item.text}
                        </span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            </motion.div>
          ))}
        </div>

        {/* Footer note */}
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8, duration: 0.5 }}
          className="text-center text-xs text-muted-foreground/35 font-light mt-10"
        >
          Questions? Contact us at info@sonuria.com · Sonuria, Inc., a Delaware Corporation.
        </motion.p>
      </div>
    </div>
  );
}
